"""empty message

Revision ID: 0ec1420e9779
Revises: 
Create Date: 2020-08-10 17:39:25.386087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec1420e9779'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accuracy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acc', sa.Float(), nullable=True),
    sa.Column('val_acc', sa.Float(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('val_loss', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confusion_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tn', sa.Integer(), nullable=True),
    sa.Column('fp', sa.Integer(), nullable=True),
    sa.Column('fn', sa.Integer(), nullable=True),
    sa.Column('tp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labeled_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(length=100), nullable=True),
    sa.Column('orca', sa.Boolean(), nullable=True),
    sa.Column('extra_label', sa.String(length=10), nullable=True),
    sa.Column('expertise_level', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_accuracy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('labeled_files', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('audio_url', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('labeling', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    op.drop_table('model_accuracy')
    op.drop_table('labeled_file')
    op.drop_table('confusion_matrix')
    op.drop_table('accuracy')
    # ### end Alembic commands ###
