"""Add date field

Revision ID: 11e033ce8ba8
Revises: f6c4432854e7
Create Date: 2020-06-24 18:06:44.891748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e033ce8ba8'
down_revision = 'f6c4432854e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeled_file', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labeled_file', 'date')
    # ### end Alembic commands ###
