"""empty message

Revision ID: 50df1df7bdff
Revises: fc7e7467f89a
Create Date: 2020-08-04 17:00:20.378030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50df1df7bdff'
down_revision = 'fc7e7467f89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeled_file', sa.Column('audio_url', sa.String(length=100), nullable=True))
    op.drop_column('labeled_file', 'filename')
    op.add_column('model_accuracy', sa.Column('labeled_files', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_accuracy', 'labeled_files')
    op.add_column('labeled_file', sa.Column('filename', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('labeled_file', 'audio_url')
    # ### end Alembic commands ###
