"""Make date indexable

Revision ID: 851b6c71001d
Revises: 11e033ce8ba8
Create Date: 2020-06-24 18:11:11.040887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851b6c71001d'
down_revision = '11e033ce8ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_labeled_file_date'), 'labeled_file', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labeled_file_date'), table_name='labeled_file')
    # ### end Alembic commands ###
