"""empty message

Revision ID: 8b1640ea4be8
Revises: 
Create Date: 2020-07-02 12:43:04.365537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1640ea4be8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labeled_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=True),
    sa.Column('orca', sa.Boolean(), nullable=True),
    sa.Column('extra_label', sa.String(length=10), nullable=True),
    sa.Column('expertise_level', sa.String(length=10), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labeled_file_date'), 'labeled_file', ['date'], unique=False)
    op.create_table('model_accuracy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_accuracy_date'), 'model_accuracy', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_accuracy_date'), table_name='model_accuracy')
    op.drop_table('model_accuracy')
    op.drop_index(op.f('ix_labeled_file_date'), table_name='labeled_file')
    op.drop_table('labeled_file')
    # ### end Alembic commands ###
