"""empty message

Revision ID: d6cf3f39b78f
Revises: 3997fca541f6
Create Date: 2020-07-23 12:12:23.768346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6cf3f39b78f'
down_revision = '3997fca541f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accuracy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acc', sa.Float(), nullable=True),
    sa.Column('val_acc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confusion_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tn', sa.Integer(), nullable=True),
    sa.Column('fp', sa.Integer(), nullable=True),
    sa.Column('fn', sa.Integer(), nullable=True),
    sa.Column('tp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_filename'), 'prediction', ['filename'], unique=False)
    op.drop_index('ix_prediction_predicted_value', table_name='prediction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_prediction_predicted_value', 'prediction', ['predicted_value'], unique=False)
    op.drop_index(op.f('ix_prediction_filename'), table_name='prediction')
    op.drop_table('confusion_matrix')
    op.drop_table('accuracy')
    # ### end Alembic commands ###
