"""empty message

Revision ID: ea75df23103b
Revises: 851b6c71001d
Create Date: 2020-06-26 12:10:33.499401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea75df23103b'
down_revision = '851b6c71001d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labeled_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=True),
    sa.Column('orca', sa.Boolean(), nullable=True),
    sa.Column('extra_label', sa.String(length=10), nullable=True),
    sa.Column('expertise_level', sa.String(length=10), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labeled_file_date'), 'labeled_file', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labeled_file_date'), table_name='labeled_file')
    op.drop_table('labeled_file')
    # ### end Alembic commands ###
