"""empty message

Revision ID: fc7e7467f89a
Revises: 713c7838d4e9
Create Date: 2020-08-04 15:50:07.710237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7e7467f89a'
down_revision = '713c7838d4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction', sa.Column('audio_url', sa.String(length=100), nullable=True))
    op.drop_index('ix_prediction_filename', table_name='prediction')
    op.drop_column('prediction', 'filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction', sa.Column('filename', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('ix_prediction_filename', 'prediction', ['filename'], unique=False)
    op.drop_column('prediction', 'audio_url')
    # ### end Alembic commands ###
